### ISSUE TITLE
Update your resume...

### ISSUE THREAD

**Issue by rfrench** [defstream/just-copy-hectorgray.com#2]
for gods sake!

**Comment by defstream** [comment]
Yup, it's about that time. I'll have it updated tonight.

![giphy](https://cloud.githubusercontent.com/assets/63482/12151233/02f55734-b463-11e5-9dbf-8eccf3ac9086.gif)

**Comment by rfrench** [comment]
👍

**Comment by defstream** [comment]
Resume updated!
